apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app.kubernetes.io/name: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
